apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "juice-shop"
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: service
  owner: assaf-enso
  lifecycle: production
  system: assaf-application-juice
  
